// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Enum_DistanceUnit
{
	KILOMETER("7602b27c-b848-4dfd-8056-dfbc95275a53"),
	STATUTE_MILE("60a499f5-437b-4d93-bacc-a087bc1c9bbb"),
	NAUTICAL_MILE("6b858289-1c18-4d55-99b5-53fbb63a824b");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DistanceUnit(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
