// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("0302517d-1cf8-493e-bbe6-6cc6e1342370"),
	startsWith("4d9ca90c-9b09-4948-a060-81c04c61b5ec"),
	endsWith("114398a1-d828-4fa0-a4f0-f8ef19664f66"),
	between("f435ba20-c30c-40ec-96d3-0b1352b54aba"),
	greater("844a73d5-8fd4-4eb7-a41d-0f05b4fdd1d1"),
	greaterEqual("2424c1ed-c4a9-4566-a420-4156aacf73f6"),
	equal("8e608371-a07f-4e5a-9c50-e62b97a88fb9"),
	notEqual("69902663-73e8-4fe4-9adf-0079e96c4cca"),
	smaller("afc10e2f-f597-40fb-9f81-d298c163092e"),
	smallerEqual("aa3fa699-4443-47ce-a90f-0492a85ae7c5"),
	empty("4b55064f-d826-4168-bc1d-6a059f11fc17"),
	notEmpty("64c6884e-8538-4b60-a18f-eece992fb8c9");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
