// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("e53890a3-9b13-4bfc-bd1e-4a6739bea8f6"),
	startsWith("4a73ce01-2526-4fde-a9d5-da4df1df287a"),
	endsWith("c35a9668-6202-4f46-9151-e836d655b4a1"),
	between("6cfae2ef-dbdc-4efd-b744-87eb93460bf6"),
	greater("acc889bf-5d13-4fad-addf-c744ca99b30f"),
	greaterEqual("788055ab-14cd-471e-9ec6-ee5f5c678756"),
	equal("b7117f91-ef7c-4141-bab9-7d9f0465115e"),
	notEqual("3f965ca9-a0ad-4aee-902e-a4471d2f5ff3"),
	smaller("3caeadac-4bba-45c7-b506-8d9dc86ff12e"),
	smallerEqual("3781f258-5b2a-454b-8aa4-66093b4db839"),
	empty("0cd2c59e-0d5c-45f7-a17b-f9a3070bd66c"),
	notEmpty("5b5d2e55-2c77-488b-aede-ffb94fcc70af");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
