// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the NativeMobile module

	public static java.lang.String getMAPTILER_API_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NativeMobile.MAPTILER_API_KEY");
	}

	public static java.lang.String getMAPTILER_MAPSTYLE_VECTOR_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NativeMobile.MAPTILER_MAPSTYLE_VECTOR_URL");
	}
}