// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("d1894095-a4f9-4827-8455-384b4ca89063"),
	English("14a52d93-cbc3-4117-9d56-735d8ee404af"),
	French("1ac401d7-68db-4c0c-b249-cebba02235f6"),
	German("d733a737-9cf5-4bdc-9f33-e9d77915bcd2"),
	Hindi("6f0a7147-50e8-4570-8dd3-216ec9f78a21"),
	Portuguese("10071846-4872-4d9e-bf93-acdbc842c3a8"),
	Spanish("db392950-c619-4296-b16a-42fff4435ce6"),
	Turkish("cda96f61-6456-45aa-a07f-0d7535feebb5");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
