// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("bf9e1113-6e65-4567-930f-52ad79a43cc1"),
	English("0e3c5c02-f609-423d-93a7-9efa800791a5"),
	French("85a5bbbf-ad48-467b-ab0a-e4a9c8bf2112"),
	German("f7754ca2-3bd9-4716-a318-3633ff5fb303"),
	Hindi("750493fc-3728-4be4-9fca-18be89feabbf"),
	Portuguese("8126750b-d4fc-49e6-a746-ba3822986678"),
	Spanish("e167ca88-8e55-4cd0-be4f-0ce284f1377e"),
	Turkish("d932f56b-d40f-4460-a6a9-c484f4783ad2");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
