// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("8c82f173-aee6-42d4-a924-df81e9a6dc9f"),
	denied("489d3f38-9a46-4a78-9d3a-09a468664839"),
	limited("a79db8df-f200-47ec-842f-ba9cfaeed18b"),
	granted("2e409cd9-0ac4-4e5c-a987-eea4b4aa956e"),
	blocked("e00d840c-7dde-4015-8ca7-54ca70928db1");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
