// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("04ec8e21-821e-467e-86bc-44e5b9a7a9b5"),
	denied("bd6a02b8-0dfc-4e43-8f07-eddab2aa09e8"),
	limited("2467b000-4038-4522-961e-af9799142edb"),
	granted("838bcae9-29bd-46c9-8898-04bb7156adf4"),
	blocked("f9a80a93-cff3-4ee5-8a20-d20386903fc4");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
