// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("38885e12-6e91-4ace-9240-ce9ff3b0a16f"),
	low("cddb2d73-ce15-4a3d-949e-a2268bc58195"),
	medium("82bb7d7f-a5d4-4b90-ae5e-900f182bfb21"),
	high("77ade63e-6665-460a-8c2c-de5d6540be39"),
	custom("5a00dab2-3e37-4e04-b3f7-8a612bb84eac");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
