// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("c3cf9e87-627d-41f9-a487-c516894ef727"),
	low("c0e01cab-3049-4840-b25a-88972a1d3dd9"),
	medium("8785ed45-c9af-4edb-a3e7-bba16d6c7594"),
	high("b6f9d312-25b1-470f-a128-ba686ad20ff6"),
	custom("0fd8e89d-9bf0-4009-8eec-216ac4e47d91");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
