// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the NativeMobile module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getMapStyleUrlBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NativeMobile.getMapStyleUrl");
		return builder;
	}

	public static java.lang.String getMapStyleUrl(IContext context)
	{
		Object result = getMapStyleUrlBuilder().execute(context);
		return (java.lang.String) result;
	}
}
