// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class MapLibre implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mapLibreMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.MapLibre";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		mapData("mapData"),
		mapStyle("mapStyle");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MapLibre(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MapLibre(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mapLibreMendixObject)
	{
		if (mapLibreMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mapLibreMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mapLibreMendixObject = mapLibreMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.MapLibre initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.MapLibre(context, mendixObject);
	}

	public static nativemobile.proxies.MapLibre load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.MapLibre.initialize(context, mendixObject);
	}

	/**
	 * @return value of mapData
	 */
	public final java.lang.String getmapData()
	{
		return getmapData(getContext());
	}

	/**
	 * @param context
	 * @return value of mapData
	 */
	public final java.lang.String getmapData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.mapData.toString());
	}

	/**
	 * Set value of mapData
	 * @param mapdata
	 */
	public final void setmapData(java.lang.String mapdata)
	{
		setmapData(getContext(), mapdata);
	}

	/**
	 * Set value of mapData
	 * @param context
	 * @param mapdata
	 */
	public final void setmapData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mapdata)
	{
		getMendixObject().setValue(context, MemberNames.mapData.toString(), mapdata);
	}

	/**
	 * @return value of mapStyle
	 */
	public final java.lang.String getmapStyle()
	{
		return getmapStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of mapStyle
	 */
	public final java.lang.String getmapStyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.mapStyle.toString());
	}

	/**
	 * Set value of mapStyle
	 * @param mapstyle
	 */
	public final void setmapStyle(java.lang.String mapstyle)
	{
		setmapStyle(getContext(), mapstyle);
	}

	/**
	 * Set value of mapStyle
	 * @param context
	 * @param mapstyle
	 */
	public final void setmapStyle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mapstyle)
	{
		getMendixObject().setValue(context, MemberNames.mapStyle.toString(), mapstyle);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mapLibreMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.MapLibre that = (nativemobile.proxies.MapLibre) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
